### ISSUE TITLE
 process-compose info to show currently running config

### ISSUE THREAD

**Issue by dzmitry-lahoda** [F1bonacc1/process-compose#100]
#### Use Case:

I want to know what config is used to run current process compose to run down command

#### Proposed Change:

 process-compose info to output currently running config path

#### Who Benefits From The Change(s)?

nix users which have path built and shored in hashed nix/store where final config hard to to find manually to call down

#### Alternative Approaches

manually find out

**Comment by F1bonacc1** [comment]
Hi @dzmitry-lahoda 

Will something like this work for you:

```shell
> ./process-compose project state
# ouput:
Hostname:          somehost
User:              someuser
Version:           v0.69.0
Up Time:           2m7s
Processes:         13
Running Processes: 11
File Names:
         - /path/to/process-compose.yaml
         - /path/to/process-compose.override.yaml
```

**Comment by F1bonacc1** [comment]
Done in v0.75.1
