### ISSUE TITLE
Add a link to the docs under the About section

### ISSUE THREAD

**Issue by lucperkins** [F1bonacc1/process-compose#108]
I had to poke around the README to find a link to the documentation. I'd recommend adding a link in the **About** section instead, like this:

<img width="274" alt="image" src="https://github.com/F1bonacc1/process-compose/assets/1523104/cda32731-30b0-4f0b-be5b-6a4463078ac4">

**Comment by F1bonacc1** [comment]
You are absolutely right!
Done.
