### ISSUE TITLE
feat: transitive dependency fails

### ISSUE THREAD

**Issue by dzmitry-lahoda** [F1bonacc1/process-compose#111]
## Feature Request

If process A depends on success(or ready) of process B and B on C;
And C fails to start/ready;
Then A should not start

#### Use Case:

Launching topology with several deps.

#### Proposed Change:

So when A depends on B success or B ready, and B does not runs at all because it depends on C,

A must never start.

#### Who Benefits From The Change(s)?

Graph like setups of  processes

#### Alternative Approaches

Make A to depend on C same way B depends on C (copy paste some yml code)

**Comment by F1bonacc1** [comment]
Thanks for pointing this out!
Fixed.
Will be a part of the next release.

**Comment by F1bonacc1** [comment]
Fixed in v0.77.4
