### ISSUE TITLE
Get process status and PID via CLI

### ISSUE THREAD

**Issue by mprimi** [F1bonacc1/process-compose#114]
Thank you for process-compose. I recently transitioned a project to it and it worked great.
The following is a request for something that would have made my life easier. I suspect others will find it useful too.

## Feature Request
I'd like to query process status via CLI. 
Specifically I'd like to get **PID** and **status** (other fields would be nice to have too, like restarts, exit code, healthchecks).

At the moment, the only commands giving me _some_ information are `process list` (which only prints names of configured processes) and `project state` (which tells me process count and process running count).

I would find it useful to have:

```
$ process-compose process status <name> --json
{name: <name>, pid: 1234, status: "running", ...} 
```

And/or:
```
$ process-compose project state --json
{
  <name_1>: {name: <name_1>, pid: 12345, status: "running", ...},
  <name_2>: {name: <name_2>, pid: 23456, status: "running", ...},
 ...
}
```

(* invalid JSON for the sake of brevity)

#### Use Case:

I'd like to know the PID in order to send signals to the running processes.

I'd like to know the state to orchestrate (confirm something is running, or not running, etc).
This mostly revolves around better troubleshooting: if I learn what is not running I can present useful error messages.

#### Proposed Change:

Add CLI commands to return process information that is currently available via TUI.
Maybe default to human-readable, but have the option for structured data (e.g., `--json`)

#### Who Benefits From The Change(s)?

I certainly do, and since I don't think I am special, this will probably help other users using `process-compose` to do similar things in a similar way.

#### Alternative Approaches

Here's the current workarounds I've had to resort to. Documenting various options for anyone else lurking on this issue in my same situation. I hope this saves you some time or gives you some ideas.

I'd love to get rid of all this junk and just query `process-compose` directly for this information.

### 1. Learning PID via process tagging and `ps | grep`
Configure processes by adding a dummy environment variable tag so they're easy to grep, e.g.

```
processes:

  FooService_1:
    command: PC_ID=foo_service_1 foo-server --config foo1.conf
```
Then learn the PID via `pid=$(ps aux | grep 'PC_ID=foo_service_1' | grep -v grep | awk '{print $2}')`

### 2. Learning PID via pidfile 
Some processes support writing a pidfile, e.g.:
```
processes:
  FooService_1:
    command: foo-server --config foo1.conf --pidfile /temp/services/foo1.pid
```
Then learn the pid via something like: `pid=$(cat ${pid_file_path})`

### 3. Write pidfile via wrapper
For processes that don't support writing a pidfile, I need to wrap via script, e.g.:
```
processes:
  FooService_1:
    command: ./scripts/write-pidfile.sh /temp/services/foo1.pid -- foo-server --config foo1.conf
```
Where `write-pidfile.sh` writes its pid to the given file then execs the arguments after the `--` separator.

### 4. Check running state via [zero signal ](https://stackoverflow.com/questions/32259228/what-is-the-zero-signal)

Once I learned the PID, my favorite way to see if something is running is via `kill -0`

**Comment by F1bonacc1** [comment]
Hey @mprimi,
Thank you for using Process Compose.
This feature for sure was on my radar, I just didn't know if there was a need for it.

BTW Have you considered something like:
```shell
# status for a single process:
curl http://localhost:8080/process/{PROC_NAME}

# statuses for all the processes:
curl http://localhost:8080/processes
```
For a single process the output will be:
```json
{
  "name": "_process2",
  "namespace": "default",
  "status": "Running",
  "system_time": "13m",
  "age": 794974605450,
  "is_ready": "Ready",
  "restarts": 0,
  "exit_code": 0,
  "pid": 4994,
  "IsRunning": true
}
```

**Comment by mprimi** [comment]
Oh my! I had completely missed the REST API! 
I have been looking at your docs up and down for the last week, and I guess I glossed over it the entire time. 🤦‍♂️

This is great.
