### ISSUE TITLE
Highlight crashed processes in red

### ISSUE THREAD

**Issue by srid** [F1bonacc1/process-compose#125]
## Feature Request

If a process exits with non-zero exit code, highlight that process line in RED colour or something. This catches the user's attention more readily than when they have to linearly (`O(n)`) scan the "EXIT CODE" column manually.

#### Use Case:

In the setup below, both the `pg-basebackup-*` processes exited unsuccessfully. (How quickly can your eyes land on them?)

<img width="1116" alt="image" src="https://github.com/F1bonacc1/process-compose/assets/3998/01414e77-7754-4d44-9a60-84fc17f44125">

#### Proposed Change

Highlight the `pg-basebackup-*` processes in different colour (red) to visually indicate that they crashed.

#### Who Benefits From The Change(s)?

Everyone, especially those who use process-compose to run more than a handful of processes.

#### Alternative Approaches

None that I can think of.

**Comment by srid** [comment]
Implementation tip:

https://github.com/F1bonacc1/process-compose/blob/24238b4c1a3d7f1629ff796d76d4d3ba5a797fb5/src/tui/proc-table.go#L37

**Comment by stijnveenman** [comment]
This is also something I've recently thought about since we had a similar need. 

One thing I personally would like to see is a status icon column (for example with just the ASCII char `●`) and giving that a color, instead of highlighting the entire row. This might improve accessibility/readability on colors.

For me, i'd like to see the following colors:
- pending: gray or yellow
- completed with exit code: 0: green
- non exit code 0: red
- running: blue

**Comment by F1bonacc1** [comment]
Added in v0.80.0
@stijnveenman I implemented your initial suggestion - it looks cleaner to me.
The lack of uniformity between the icon (ASCII chars) styles bugged my OCD too much :)
As for the color-blind people, the state can be inferred from the text as well.

**Comment by srid** [comment]
@F1bonacc1 Nice!

This is what it looks like, btw.

- Should 'skipped' be in yellow, same as 'not ready'?

<img width="809" alt="image" src="https://github.com/F1bonacc1/process-compose/assets/3998/0224d07c-92c4-4972-b6e0-4e848a924f59">

**Comment by F1bonacc1** [comment]
Hi @srid,
I am always open to feedback; if something can be improved, I am all for it.
Skipped means one of the 2 failed states:
1. Process A waited for B to finish with exit code 0, but it didn't.
2. Process A waited for B to become ready but B finished without becoming ready.
