### ISSUE TITLE
[feature request] Allow disabling the REST API

### ISSUE THREAD

**Issue by cole-h** [F1bonacc1/process-compose#126]
#### Use Case:
I use `process-compose` in a couple of projects. However, the REST API `process-compose` exposes conflicts with both itself (when trying to run multiple instances of `process-compose` in different projects) and with other software (i.e. webservers that bind to 8080 locally, the default REST API port).

#### Proposed Change:
I would like a way to completely disable the REST API webserver that comes with `process-compose` -- I don't need it.

#### Who Benefits From The Change(s)?
Anybody who wants to use `process-compose` in multiple projects at the same time.

#### Alternative Approaches
None.

**Comment by F1bonacc1** [comment]
Hi @cole-h,

Have you considered, as an alternative, specifying a different port for each instance of Process Compose with `-p` flag or the `PC_PORT_NUM` environment variable?

**Comment by cole-h** [comment]
I have, but it is quite inconvenient to remember to do that whenever I start using `process-compose` in a new project (for me, this is more frequent than you may think).  I'll try to start it up, but it just silently exits with status code 1 and no output.

It's very convenient being able to run `process-compose` and get a working environment with all my required background processes without needing to remember to specify a flag or environment variable.

**Comment by F1bonacc1** [comment]
Will something like `--no-server` flag that you will be able to add to your Process Compose alias, work for you?

**Comment by cole-h** [comment]
Yes it would! If I may be greedy, I'd also appreciate an environment variable. (It's easier to set a global environment variable that disables the server altogether than it is to set lots of scoped environment variables to change the port.)

**Comment by F1bonacc1** [comment]
Sure, it's almost the same effort to add them both.

**Comment by F1bonacc1** [comment]
Added in v0.80.0

**Comment by cole-h** [comment]
Thanks a ton for being amenable and for the quick turnaround! I really appreciate it!
