### ISSUE TITLE
Easier way to scan the "RESTARTS" column

### ISSUE THREAD

**Issue by srid** [F1bonacc1/process-compose#128]
## Feature Request

Make it easier to look for non-zero numbers in the RESTARTS column.

#### Use Case:

When you have 20 processes, and only one of them has restarted non-zero of times, I'd like to see which process that is by a quick scan.

#### Proposed Change:

Replace `0` with `-` (or even empty cell)

In this example, kafka has restarted 3 times (no other processes restarted) -- which had us file https://github.com/juspay/services-flake/issues/72 -- but you have to more or less do a O(n) scan of the RESTARTs column to get to it. Can we visually make it easy to spot that?

![image](https://github.com/F1bonacc1/process-compose/assets/3998/ca1d3e9d-4e70-47a1-b49e-1a4f8b2071ff)

#### Who Benefits From The Change(s)?

Everyone?

#### Alternative Approaches

None I can think of.

**Comment by F1bonacc1** [comment]
Hi @srid,
As an alternative, did you try sorting the processes by the restart count, `SHIFT-R` in this case?

**Comment by srid** [comment]
That's a good alternative, though I'd say having a quick way to visually scan would be nice as well.

**Comment by F1bonacc1** [comment]
Hi @srid,

I tried the proposed approach to show only positive restarts count.
The empty cell disagrees with my OCD and doesn't look well when there are no restarts at all:
![image](https://github.com/F1bonacc1/process-compose/assets/806740/4d4d28c8-4fe9-4ab4-a953-e718f24c167e)

If I use `-` it looks better:
![image](https://github.com/F1bonacc1/process-compose/assets/806740/48bb28fe-edbc-4992-abe8-3122eec6d48e)

I also tried to use the bold font style, at least in my terminal the difference is invisible...
Then I tried a slightly darker blue:
![image](https://github.com/F1bonacc1/process-compose/assets/806740/68420649-fb6f-41e5-be3d-bdfcf37c3880)

Which one do you think looks the best?
👍🏻 - First image.
🎉 - Second image.
🚀 - Third image.

**Comment by thenonameguy** [comment]
Probably use the same for exit code column (and maybe have the same for age/health) as well? Just to be consistent.

**Comment by srid** [comment]
@F1bonacc1 Interesting. 

I'd say the second image (using `-`) is better (I see there are already 3 votes for it.)

In regards to the third image, the color difference is not super obvious, so it looks more or less like the first image

> Probably use the same for exit code column (and maybe have the same for age/health) as well? Just to be consistent.

Yeah, agreed.

**Comment by srid** [comment]
> Probably use the same for exit code column (and maybe have the same for age/health) as well? Just to be consistent.

I also noticed how the exit code column shows `0` for processes that are _still_ running. How can a running process have a exit code (here, `0`)?

**Comment by F1bonacc1** [comment]
Will be part of the next release.

**Comment by F1bonacc1** [comment]
Added in v0.81.4
Please let me know if it works as expected.
