### ISSUE TITLE
Keep TUI running even if all processes crash

### ISSUE THREAD

**Issue by srid** [F1bonacc1/process-compose#129]
## Feature Request

When there's no process left to run, process-compose silently exits. Unless I have `log_file` enabled, there's no way to peek at the error messages of the various processes. Can an option be added to keep the TUI on, perhaps with a red error message saying no processes is running?

#### Proposed Change:

Can an option be added to keep the TUI on, perhaps with a red error message saying no processes is running?

#### Who Benefits From The Change(s)?

Everyone.

#### Alternative Approaches

I use `-t=false` which leaves the logs on the screen as the command exists, but this is not easy to read when you are running 20+ processes.

**Comment by F1bonacc1** [comment]
Added in v0.81.4
Please let me know if it works as expected.
