### ISSUE TITLE
More clear error reporting iIf port 8080 is blocked

### ISSUE THREAD

**Issue by pmiddend** [F1bonacc1/process-compose#130]
Took me 20min just now to realize why `process-compose` simply exited with exit code 1 when I try to run my `yaml` file: port 8080 is already taken on my machine.

1. Why does it try to bind to this port? Is this configurable?
2. I had to find out that the log file is in `/etc/process-compose-$(whoami).log` and that the error is there. Since this is an initialization error, wouldn't it be more user-friendly to display it directly on stderr?

**Comment by F1bonacc1** [comment]
Fixed. Will be part of the next release.

**Comment by F1bonacc1** [comment]
Fixed in v0.81.4
