### ISSUE TITLE
Toggle visibility of disabled services

### ISSUE THREAD

**Issue by jankramer** [F1bonacc1/process-compose#133]
## Feature Request

It would be great if we could toggle the visibility of disabled services at run-time.

#### Use Case:

I love the feature introduced in #123. However, in one of the projects I use process-compose, there are around 200 processes. Of these services, typically only a handful are actually running. Before v0.77.8, the process overview would be very clear, but now with all the disabled processes it is less readable.

#### Proposed Change:

If a user would be able to toggle the visibility of disabled processes, this would allow the overview to remain clear during normal use, and if we want to start an additional process that wasn't started yet, you can easily use the toggle to find and start the process, without having to restart every service.

#### Who Benefits From The Change(s)?

Users with many processes that typically only run a small subset.

#### Alternative Approaches
Sorting the process list by PID does group the processes that are currently running, but that prevents users from sorting by any other column.

**Comment by F1bonacc1** [comment]
Hi @jankramer,

There some additional alternatives that should be considered:
1. Using namespaces there is an existing toggle to show/hide namespaces.
2. Using the `-d` flag to start without the disabled processes (not at a toggle).
3. Using the `-n` flag to start only a specified list (`-n NS1 -n NS2 ...`) of namespaces.

If none of that works for your use case. What shortcut would you recommend for the proposed toggle?

**Comment by jankramer** [comment]
Hi @F1bonacc1,

Thanks for the suggestions!

1.  Namespaces are not the best fit for this use case because processes are used across multiple domains, but can only be in 1 namespace in process-compose (understandably!).
2. Starting with the `-d` flag would indeed solve the readability issue, but then we can no longer quickly start a disabled process without having to restart process-compose. I was actually quite happy that this is now possible since v0.77.8.
3. The `-n` flag suffers from the same limitation as mentioned in 1.

If the shortcut `CTRL+D` is still free, that would be my recommendation.

**Comment by F1bonacc1** [comment]
Added in v0.85.0.

**Comment by jankramer** [comment]
Awesome, just tried it out, and it works great. Thanks for your efforts!
