### ISSUE TITLE
Show why a process is in PENDING state

### ISSUE THREAD

**Issue by srid** [F1bonacc1/process-compose#134]
## Feature Request

When a process perpetually remains in PENDING state, allow a way for the user to see *why* it is in pending state.

#### Use Case:

Let's say a process Foo `depends_on` on some state of 7 other process. If Foo is pending, how does the user know which of the 7 processes is causing it to be pending? 

Right now they have to look at the YAML file (or the code that generates it) and do a O(n) scan for all those processes. This doesn't scale.

#### Proposed Change:

Add a keybinding, column or something that enables the user to instantly see which relationship is causing the PENDING state. For bonus points, allow navigating to the process in question.

#### Who Benefits From The Change(s)?

Everyone that uses non-trivial config.

**Comment by F1bonacc1** [comment]
Hi @srid,

You can see the list of dependencies in the process info dialog (`F3`).

**Comment by srid** [comment]
Ah, yes, thanks!

<img width="1077" alt="image" src="https://github.com/F1bonacc1/process-compose/assets/3998/65a6b1fa-7fd4-47d8-80bb-5025afe19972">

I'll close this issue. I do think it would be nice to show the 'current blocking process' directly in the UI; I'll think about this.
