### ISSUE TITLE
color log output

### ISSUE THREAD

**Issue by colemickens** [F1bonacc1/process-compose#141]
## Feature Request

I found a past issue about this, but I'm definitely not seeing color output in my process-compose windows.

For reading my application logs, the loglevel colors are very helpful, but lost when run through process-compose.

v0.80.0

**Comment by colemickens** [comment]
Hm, thanks for the tips, but shouldn't `process-compose` be able to roughly do what apps like `tmux` and `zellij` too? If I squint, `process-compose` is a glorified multiplexer after all.

**Comment by thenonameguy** [comment]
It could and probably should :)
That's the point of ticket #64, where it turned out it's not a simple addition to do, therefore workaround are needed for the time being.

IMO we can close this ticket as a duplicate and continue there.
