### ISSUE TITLE
Brand the TUI

### ISSUE THREAD

**Issue by blaggacao** [F1bonacc1/process-compose#143]
Not without due credit, of course, I want to craft a user experience on the shoulders of Project Compose.

Not always, though, that level of detail knowledge about the stack is user-relevant (really depends on the user you have).

It may rather be a distraction. so in my case.

Would it be possible to rebrand the "Process Compose" string in the tui (and maybe elsewhere)?

Precendent spotted: https://paisano-nix.github.io/tui/rebranding-nix.html

**Comment by F1bonacc1** [comment]
Hi,

That's an interesting proposition.
That's an easy change and I can add it to the next version.

It sounds like rebranding is something only organizations would be interested in 😃
Maybe in the future, I will convert it to a Pro feature 😃 along with https support.

**Comment by blaggacao** [comment]
Concretely, I'd like to use it for https://github.com/blaggacao/frappix, but I can see how organizations would like to use it, too.

Thanks for considering it!

**Comment by F1bonacc1** [comment]
Added in v0.88.0
