### ISSUE TITLE
Support for colorschemes

### ISSUE THREAD

**Issue by buntec** [F1bonacc1/process-compose#144]
Thank you for this great project! I would love to see support for colorschemes e.g., via `$XDG_CONFIG_HOME/process-compose/colors.yaml`. Looks like it would only require a handful of color definitions. I frequently have process-compose open inside a tmux pane for hours on end and it would be really nice if I could match my vim/tmux/etc theme.

**Comment by silky** [comment]
Agree; I think this is pretty essential given that process-compose seems to default to a dark-mode colouring rather than the system preferences :)

**Comment by F1bonacc1** [comment]
Added in v1.0.0
