### ISSUE TITLE
warn about impossible conditions

### ISSUE THREAD

**Issue by teto** [F1bonacc1/process-compose#153]
## Feature Request
warn if conditions can not be satisfied
Out of curiosity I added the following condition to a process (e.g, waiting for postgres to be up) wihout setting up a healthprobe on postgresql.
```
    depends_on:
      postgresql:
        condition: process_healthy
```
so it turns out that my process with never start.

#### Use Case:
avoid mistake/help the user write his configuration

#### Proposed Change:

It might be useful to add a warning in that case (in F3, the process details) or instead of pending mark as "Impossible". In the logs at least.

#### Who Benefits From The Change(s)?
users

**Comment by F1bonacc1** [comment]
Hey @teto,

Thanks for all the improvement recommendations.
I will add a better warning to the next release.

**Comment by F1bonacc1** [comment]
Added in v1.0.0.
