### ISSUE TITLE
redraw "process window" after resize events

### ISSUE THREAD

**Issue by teto** [F1bonacc1/process-compose#154]
There are some oddities in the display of "command" when showing "process details" (f3)  in a narrow window:

```
➜ echo $COLUMNS
127
```
process-compose shows the end of my command instead of the beginning
![image](https://github.com/F1bonacc1/process-compose/assets/886074/c1396ef7-61a3-495a-9e5e-a728197ee177)

and it remains the same if I go fullscreen.
Now if I close the "Process details" window and reopen it while being fullscreen, it shows correctly.

NB: Sorry to open several issues in a row, it's not to pressure any opensource developers, just to track issue. This is a fairly minor issue I dont mind it.

**Comment by F1bonacc1** [comment]
Fixed in v1.34.0
