### ISSUE TITLE
multiline command can easily get ignored/discarded

### ISSUE THREAD

**Issue by teto** [F1bonacc1/process-compose#156]
If I configure the following process
```
  simworker:
    namespace: core
    command:
      source pgtemp.env
      nix run .#simworker
```
then it's considered as complete but it looks like it does nothing (or possibly just run the first line)
![image](https://github.com/F1bonacc1/process-compose/assets/886074/570f5905-f030-4bbe-b5f2-798862604a06)

Now if you add a pipe to tell yaml to expect a multiline command and the last line of command is executed correctly
```
  simworker:
    namespace: core
    # NOTICE THE PIPE
    command: |
      source pgtemp.env
      nix run .#simworker
```

The current behavior might make sense from a YAML perspective etc but from the user perspective, I feel like a warning could help

**Comment by F1bonacc1** [comment]
Multiline support is compliant with yaml specifications.
To make things clearer, I added [documentation](https://f1bonacc1.github.io/process-compose/configuration/#misc) for all the supported variants of multiline commands.
