### ISSUE TITLE
How to focus the upper panel (with the list of services) instead of the log ? 

### ISSUE THREAD

**Issue by teto** [F1bonacc1/process-compose#159]
in TUI, I've realized that some mappings dont work when the log panel is focused (for instance restarting the service). It doesnt seem to me that this needs to be this strict though I could understand why it's done like this (per mapping component). In which case I would like to know if there is a mapping to switch between the "service panel" and the "log panel" ?
![image](https://github.com/F1bonacc1/process-compose/assets/886074/e1f4fb7d-7dad-4e6c-bbc4-c01915be3585)

I propose that we restart the currently selected service even when focusing the log panel but not sure about the implications.

**Comment by F1bonacc1** [comment]
Added toggle focus support (`TAB`) in v1.0.0.

**Comment by teto** [comment]
awesome ty
