### ISSUE TITLE
Better use of (visual) screen assets

### ISSUE THREAD

**Issue by blaggacao** [F1bonacc1/process-compose#161]
I think these can be placed in one row to save on valuable screen space.

![image](https://github.com/F1bonacc1/process-compose/assets/7548295/8b485dba-2164-4b70-87b5-0d73b91a9d1a)

On a crowded tile, process-compose doesn't really shine, because with the little space left you only see common place info.

**Comment by blaggacao** [comment]
> On a crowded tile, process-compose doesn't really shine, because with the little space left you only see common place info.

For the same reason, it's probably worth a consideration to get rid of some of the border lines,

![image](https://github.com/F1bonacc1/process-compose/assets/7548295/c52e7261-4250-4301-b8d9-86a2dbffdacd)

**Comment by blaggacao** [comment]
If custom shortcuts are configured, the help line could disappear, too. Or show up on pressing `h` or something (`F1` :smile: )

**Comment by blaggacao** [comment]
pretty crowded example:

![image](https://github.com/F1bonacc1/process-compose/assets/7548295/1d9f78bc-9f2c-496e-9177-20ef66b94a28)

**Comment by F1bonacc1** [comment]
Hey @blaggacao,

Will something like `F11` (full screen) shortcut be an acceptable solution?

**Comment by blaggacao** [comment]
Typically, not, unfortunately. I really need that screen asset, typically, I'd look on the smallest screen with the logs just for some signal from the corner of my eye, and only if there's something interesting, I'd then go and look and go full ofscreen (which in my case is just `Mod1+RMiddleUp`).

Since I do that anyway once in a while, that's not the issue here. The issue, I perceive, is really to maximize screen asset as much as possible.

In my own project (`paisano-nix/tui`) I also went with nice frames and spaces and optimized for "good looking", but now I regularly swear upon myself for that choice for the exact same reasons laid out here.

In the end, it's just my own perspective that I bring to the table, and it's clear that there may be differing preferences.

**Comment by blaggacao** [comment]
Ah! I completely got you wrong! Yeah, that would be really nice. Sorry, that I didn't get the angle.

**Comment by F1bonacc1** [comment]
No worries :)

**Comment by F1bonacc1** [comment]
Added in v1.0.0.
Use `CTRL-]` to toggle
