### ISSUE TITLE
copy/paste interrupted by log panel redraws

### ISSUE THREAD

**Issue by teto** [F1bonacc1/process-compose#162]
I have some trouble copy/pasting from process-compose (PC) 0.88 log panel with kitty on wayland. 
I tried to `unfollow` the log but even then, when I start selecting text, PC seems to redraw the screen which breaks my selection. 
Not redrawing the log panel should fix this.

**Comment by teto** [comment]
I am not sure they are the same, I use the terminal copy mode that should be independant of the application, and I can copy/paste with process-compose, just the selection gets interrupted by kitty because of the terminal redraws I suppose (not 100% sure though) ?

**Comment by F1bonacc1** [comment]
Unfortunately, I had to disable the selection mode in Wayland sessions.
You can try it by unsetting the `WAYLAND_DISPLAY` env variable.
