### ISSUE TITLE
possibility to send process-compose to background

### ISSUE THREAD

**Issue by teto** [F1bonacc1/process-compose#163]
## Feature Request
I like sending the current program to the background with Ctrl+Z so that I can quickly cheeck something in the current directory and put back the program to foreground with `fg`.
`process-compose` seems to catch the Ctrl-z signal and does nothing with it ? 

#### Who Benefits From The Change(s)?
Probably not everyone

**Comment by F1bonacc1** [comment]
Added in v1.0.0.
`CTRL-B` to send to the background, exit the shell (`CTRL-D`) to return.

**Comment by teto** [comment]
wonderful. the default binding to send to background is usually Ctrl-Z, could it be made the default instead ?

**Comment by F1bonacc1** [comment]
Sure, you can change it in your `shortcuts.yaml`.

**Comment by teto** [comment]
I know but is there a compelling reason for upstream to use a different default than 99% of all software ?

**Comment by F1bonacc1** [comment]
The implementation is slightly different than `sigtstp` and `sigcont`. Since I want the process to keep running and receive cpu time.
Do you think it should be suspended like programs that are sent to the background with `CTRL-Z`?

**Comment by teto** [comment]
If the behavior is different, I understand better your choice. As you mentioned it can be overriden

> Since I want the process to keep running and receive cpu time.

why do we need that ? for the probes to run ?

**Comment by F1bonacc1** [comment]
That's right:
* probes
* log aggregation and rotation
* API server
* processes orchestration

**Comment by teto** [comment]
great thanks !
