### ISSUE TITLE
merge with any other decent terminal multiplexer

### ISSUE THREAD

**Issue by colemickens** [F1bonacc1/process-compose#168]
Can process-compose please combine forces with zellij or something? I'm losing my mind trying to do basic things like "get colored output" or "copy text out of the log window".

**Comment by colemickens** [comment]
also, I'm paging down in one of my processes now and ... it's just going forever.. I know there isn't this much output.

**Comment by colemickens** [comment]
really though, what on earth is it doing? As I page down I can see the exact sme output flying by over and over.

**Comment by F1bonacc1** [comment]
Hey @colemickens,

Is this a feature request or a bug?
I'm not sure what is the ask here.

**Comment by colemickens** [comment]
Sorry, this is neither a good bug report, nor a good feature request. Thanks for process-compose!
