### ISSUE TITLE
liveness probe logic does not match the docs

### ISSUE THREAD

**Issue by laojianzi** [F1bonacc1/process-compose#170]
hi @F1bonacc1 

sorry, i don't see a restart anywhere, am I missing something?

https://github.com/F1bonacc1/process-compose/blob/main/www/docs/health.md#configure-probes
> When a probe fails, Process Compose will try failure_threshold times before giving up. Giving up in case of liveness probe means restarting the process.

https://github.com/F1bonacc1/process-compose/blob/caa1a4d28793520f28643004bd5de62496ebaad7/src/app/process.go#L629-L635

**Comment by F1bonacc1** [comment]
Hey @laojianzi 
You are right. It's a bug in the documentation. The described behavior is for the readiness probe.
I will fix it.

Thank you for letting me know!

Cheers!

**Comment by F1bonacc1** [comment]
Fixed the docs
