### ISSUE TITLE
Support unix socket for HTTP

### ISSUE THREAD

**Issue by domenkozar** [F1bonacc1/process-compose#172]
See https://github.com/cachix/devenv/issues/1091

**Comment by F1bonacc1** [comment]
Hey @domenkozar,

Can you please explain what is the ask here?
Maybe the flag `--no-server` to disable the process-compose server can help?

**Comment by domenkozar** [comment]
Currently port 9999 is opened and I would like to see support for UNIX sockets, so that multiple process-compose can run in parallel.

**Comment by thenonameguy** [comment]
What Domen is asking for really is a file-based socket, that is easy to spawn more of.
The port 9999 is just [a default value for devenv](https://github.com/cachix/devenv/blob/main/src/modules/process-managers/process-compose.nix#L54) as the current default port commonly conflicts with other HTTP servers.

**Comment by adrian-gierakowski** [comment]
You can run multiple instances of PC at different ports

**Comment by thenonameguy** [comment]
> You can run multiple instances of PC at different ports

Thanks, but this is clear to everyone, see the original reply from @domenkozar from yesterday:
https://github.com/cachix/devenv/issues/1091#issuecomment-2031063105

To be able to provide an automatic way in devenv to not have port conflicts (without remembering which ports are taken), a file-based socket with a random name allows an external wrapper of process-compose to handle this.

**Comment by thenonameguy** [comment]
```mermaid
graph TD
    subgraph project1[Random Project 1]
        devenv-1[devenv]
        process-compose-1[Process Compose port 9999]
        
        devenv-1 --> process-compose-1
    end

    subgraph project2[Random Project 2]
        devenv-2
        process-compose-2[Process Compose port 9999]
        devenv-2 --> process-compose-2
    end
 ```
 The goal would be to support running 2 random projects at the same time on the same host, without modifying anything.
 Think of picking 2 random devenv/process-compose projects of of Github.

**Comment by F1bonacc1** [comment]
To sum up:
1. The default behavior will be port based.
2. I will provide a flag to start with UDS with ports disabled.
3. The socket file name is optional (?).
4. The UDS mode won't be available on Windows.

**Question**: If no socket file name is provided should the default be random:  `/tmp/process-compose-<random>.sock` or predefined: `/tmp/process-compose.sock`?

Random advantage:
* Can start multiple projects with 0 configuration.
Predefined advantage:
* Clients can connect without additional flags (except UDS mode).

**Comment by adrian-gierakowski** [comment]
If PC decides a random socket file, how would the client know which file to use when connecting?

**Comment by thenonameguy** [comment]
Here's how the Clojure NREPL server solves it (that does random port assignment):
It randomly chooses an open available port at runtime and writes the number to a gitignored `.nrepl-port` file.
Clients then always look at that file (or the closest file like by walking up the FS tree) to know which port to connect to.

A similar approach could be done with the UDS, although with the above, it might not even be necessary.

**Comment by domenkozar** [comment]
> To sum up:
> 
> 1. The default behavior will be port based.
> 2. I will provide a flag to start with UDS with ports disabled.
> 3. The socket file name is optional (?).
> 4. The UDS mode won't be available on Windows.
> 
> **Question**: If no socket file name is provided should the default be random: `/tmp/process-compose-<random>.sock` or predefined: `/tmp/process-compose.sock`?
> 
> **Random advantage:**
> 
> * Can start multiple projects with 0 configuration.
> 
> **Predefined advantage:**
> 
> * Clients can connect without additional flags (except UDS mode).

What's important for devenv is to be able to specify the socket path, as we want to store it into `DEVENV_RUNTIME` to avoid long paths that sockets are sensitive to.

Something like defaulting to `TMPDIR/process-compose-{pid}.pid` and being to override it with `PC_SOCKET_PATH` would be ideal.

**Comment by F1bonacc1** [comment]
Added in v1.2.0

**Comment by domenkozar** [comment]
Thank you!
