### ISSUE TITLE
Search cancellation doesn't work properly

### ISSUE THREAD

**Issue by stijnveenman** [F1bonacc1/process-compose#174]
## Defect
I like the new low profile search bar. However, it seems to cause some weird behaviour when cancelling the search. 

#### Version of `process-compose`:
v1.2.0 (and v1.0.1)

#### OS environment:
Mac M1

#### Steps or code to reproduce the issue:
- start searching with `/`
- filter out a few processes
- press escape

#### Expected result:
The search bar should close

#### Actual result:
The search is cancelled, (all processes are visible again). But the search bar is still there, and any next input is added to the search, triggering the search filter again.

**Comment by F1bonacc1** [comment]
Fixed in v1.5.0
Please let me know if it works as expected now.
