### ISSUE TITLE
Non-json logs are prefixed with `[90m<nil>[0m`

### ISSUE THREAD

**Issue by cor** [F1bonacc1/process-compose#178]
## Defect

Non-json logs are prefixed with `[90m<nil>[0m`. Happens with any possible configuration

Make sure that these boxes are checked before submitting your issue -- thank you!
#### Version of `process-compose`:

Latest commit on main, built from nix flake

#### OS environment:
NixOS 23.11

#### Steps or code to reproduce the issue:

Write any logs with

```json
      "log_configuration": {
        "disable_json": true,
        "no_metadata": true
      },
```

and specify a path with
```json
  "log_location": "./example.log",
```

write some logs, then open `./example.log` in your editor

#### Expected result:

No `[90m<nil>[0m` at the start of each line

#### Actual result:

`[90m<nil>[0m` at the start of each line

**Comment by F1bonacc1** [comment]
Hi @cor,

Did you try adding `no_color: true`?

```yaml
log_configuration:
  disable_json: true
  no_color: true # <-- add this
```
