### ISSUE TITLE
Networking capabilities

### ISSUE THREAD

**Issue by jostillmanns** [F1bonacc1/process-compose#185]
Thanks for all your effort on creating this. process-compose looks super cool.

I am researching process-compose and similar software right now to run dev environments without containers. devenv.sh seems to make a good job here and I like to see process-compose be a central part of this.

What I am curious about though is the whole networking aspect of this. Specifically running the same service mutliple times on the same host. I would suspect that doing this with process-compose would fail, since the OS, or linux would forbid me to allocate, listen to the same port twice. Linux provides capabilities to create new network devices or even network namespaces to support this usecase. Was there ever plans to extend functionality of process-compose to support this use case?

**Comment by F1bonacc1** [comment]
Hey @jostillmanns,

I am glad you find Process Compose useful.
Does issue https://github.com/F1bonacc1/process-compose/issues/172 address what you are after?

**Comment by jostillmanns** [comment]
That looks extremely close to what I am looking for. Will look more in detail later. Thanks for your quick response!

**Comment by thenonameguy** [comment]
@jostillmanns based on your OP, you are looking to isolate individual processes WITHIN process-compose, correct? So you want to run nginx for instance on port 8080, in 2 isolated network namespaces on the same host.

This is not covered at the moment at all by process-compose (and probably it shouldn't).
I would recommended solving this within the command/with a wrapper bash script for now.

The mentioned UDS feature is for running multiple process-compose instances, but that doesn't solve the problem that you only have a single network namespace on the machine.

**Comment by jostillmanns** [comment]
Actually, I was looking to isolate process-compose instances, not individual processes. But thinking about this now, maybe this even is also a requirement. Thanks for your insights!
