### ISSUE TITLE
Allow readiness dependencies to wait through process restarts

### ISSUE THREAD

**Issue by shlevy** [F1bonacc1/process-compose#189]
#### Use Case:

In some cases, a failed readiness probe can only be remedied by a restart, but after healthy restart we want downstream processes to get started

#### Proposed Change:

Add `process_healthy_restart_allowed` as a dependency condition, then the process will stay in `pending` until the process it depends on is healthy (even if restarts are needed) or it will be skipped if the dependent process’s `max_restarts` are met

#### Who Benefits From The Change(s)?

Those using crash-only designs

#### Alternative Approaches

Put the process restart into the process script itself, rather than using process-compose’s orchestration

**Comment by F1bonacc1** [comment]
Hey @shlevy,

Thanks for reporting this, it should have been the default behavior.
I will deliver a fix in the next version.

**Comment by F1bonacc1** [comment]
Released in v1.9.0
