### ISSUE TITLE
Disable loading .env file

### ISSUE THREAD

**Issue by shyim** [F1bonacc1/process-compose#192]
## Feature Request

Right now process compose loads the project `.env` file and makes it impossible to change any configuration while the processes are running.

I would like to have a flag in the configuration to disable this behavior. I set all relevant environment variables already before calling process compose

**Comment by F1bonacc1** [comment]
Hi,

I can provide an argument and an environment variable to disable the `.env` loading.
Do you think it will work for you?

**Comment by F1bonacc1** [comment]
Just so you know, `process-compose` (with `.env` file) doesn't override an env variable that already exists.

**Comment by shyim** [comment]
I want that my application reads the `.env` and so I can change the environment variable **without** restarting process compose

**Comment by F1bonacc1** [comment]
That makes sense.
Will the process compose argument to disable .env loading help you then?

**Comment by shyim** [comment]
yes or in the config file in the root level maybe :)

**Comment by F1bonacc1** [comment]
Released in v1.9.0

**Comment by RafaelKr** [comment]
v1.9.0 is now available on nixpkgs unstable: https://search.nixos.org/packages?channel=unstable&show=process-compose&from=0&size=50&sort=relevance&type=packages&query=process-compose
