### ISSUE TITLE
Support hjkl navigation in TUI modals

### ISSUE THREAD

**Issue by thenonameguy** [F1bonacc1/process-compose#193]
## Feature Request

Allow using `hjkl` binding in the Quit? modal as an alternative to arrow navigation.

#### Use Case:

Vimmers wanting to vim everywhere

#### Proposed Change:

https://github.com/F1bonacc1/process-compose/blob/3cd252df8d3a6852aea56efddf5f77eece7d5406/src/tui/view.go#L292

#### Who Benefits From The Change(s)?

https://github.com/cachix/devenv/issues/1272#issuecomment-2165448213

**Comment by F1bonacc1** [comment]
Added in v1.18.0

Cheers ✌🏻
