### ISSUE TITLE
read flags from config file?

### ISSUE THREAD

**Issue by smeijer** [F1bonacc1/process-compose#194]
Is it possible to add cli options to the `process-compose.yaml` ? Such as starting in full-screen mode (`ctrl + ]`) or changing the manager port not via env but controlling it via the config file, or the `-t=false`, etc?

**Comment by Qqwy** [comment]
In the same vein: one of our services runs on port 8080. While we can make sure to always start `process-compose` with `-p 8081`, it would be much nicer if that could be encapsulated in the configuration.

We've tried setting `PC_PORT_NUM=8081` in the environment section of the `process-compose.yaml` as well, but it seems that this environment setting is not used for the configuration of process-compose itself.

**Comment by F1bonacc1** [comment]
That's a good proposal.
I think it was already discussed in the past, but I can't find the issue right now :)

### Background
So far the PC philosophy was to separate the business logic configuration (processes and orchestration) from preferences and environment considerations (themes, tui, ports).

The idea behind it is portability and the ability to manage `process-compose.yaml` files in source control. If you change it and commit it, it should be applicable for all the environments, all the local changes are kept local (not in source control).

Having said that, I see how @Qqwy's use case breaks at least some of those assumptions. Of course, there is also a possibility that a `process-compose.yaml` configured port in environment A will not be free in environment B. Thus creating more unwanted commits.

### Proposal
* What do think about a `.pc_env` file that won't interfere PC `.env` and with other `.env` using processes, that will contain all the local PC settings?
* Another alternative is to add (at least some of) those preferences to the [TUI settings](https://f1bonacc1.github.io/process-compose/tui/#tui-state-settings) file. It won't cover all the use cases mentioned, but might be more user-friendly in some scenarios.

**Comment by smeijer** [comment]
That works for me and makes a lot of sense. Thanks!

**Comment by F1bonacc1** [comment]
Added in v1.18.0

Cheers ✌🏻

**Comment by unhammer** [comment]
I've read https://f1bonacc1.github.io/process-compose/tui/#tui-state-settings but can't find how you set it to start full-screen? Ideally I'd want it to start full-screen, logs maximized and unwrapped, since I keep having to do
`F4 F6 Ctrl+]` 
every time I start it
