### ISSUE TITLE
Add Go templating for probe http port

### ISSUE THREAD

**Issue by DanieleIsoni** [F1bonacc1/process-compose#196]
## Feature Request

It would be useful to add templating for `processes.process.<probe>.http_get.port`

#### Use Case:
We use process compose to manage tunnels to some services so it would be great to template the probes using vars

#### Proposed Change:
Adding the possibility to use variables in `processes.process.<probe>.http_get.port`

#### Alternative Approaches
I cannot think to alterative approaches

**Comment by F1bonacc1** [comment]
Added in v1.18.0

Cheers ✌🏻
