### ISSUE TITLE
Distinguish between stopped processes and processes that don't exist

### ISSUE THREAD

**Issue by zmitchell** [F1bonacc1/process-compose#198]
## Feature Request
Show a different error message when attempting to stop a process that is no longer running vs. attempting to stop a process that never existed in the config.

#### Use Case:
One of these indicates a user error (perhaps you made a typo entering the process name), and one of these indicates that a process may have terminated earlier than you expected. These are two different cases and a user may want to take different actions based on which error they encounter.

#### Proposed Change:
There's already an internal record of which processes exist because completed processes are shown in `process-compose process list`. You can use this record to disambiguate between these two cases.

#### Who Benefits From The Change(s)?
Everyone

**Comment by F1bonacc1** [comment]
Added in v1.18.0

Cheers ✌🏻
