### ISSUE TITLE
Add support for colored logs

### ISSUE THREAD

**Issue by thenonameguy** [F1bonacc1/process-compose#20]
Currently ASCII color codes are lost in the TUI process log view. 
It would be nice to have an option to actually interpret them in the terminal, as an opt-in flag in the process definition (no breakage).

**Comment by F1bonacc1** [comment]
Hi @thenonameguy 
I like this idea a lot!
I will check if there is a way to make it work with the third party I use today.

**Comment by F1bonacc1** [comment]
Hi @thenonameguy 

The logs look definitely better in [v0.24.0](https://github.com/F1bonacc1/process-compose/releases/tag/v0.24.0)
