### ISSUE TITLE
Don't shut down process-compose unless requested

### ISSUE THREAD

**Issue by zmitchell** [F1bonacc1/process-compose#200]
## Feature Request
Currently `process-compose` terminates if all the running processes are stopped. I think it would be better if it continued to run until it was requested to shut down.

#### Use Case:
Suppose you make a config whose processes all terminate unexpectedly (maybe the commands you entered were wrong). You then go to see the status of your processes and get an error because the server has already shut down. If you're using Unix sockets you may even get an unexpected error about a file not existing since `process-compose` cleans up the socket when it shuts down. The user in this case has no indication as to why `process-compose` has shut down, or that the root cause it that their processes terminated abruptly.

#### Proposed Change:
Keep `process-compose` alive until the user requests that it should terminate.

#### Who Benefits From The Change(s)?
Anyone running `process-compose` in the background without the TUI e.g.
```
$ process-compose up -f <config> -u <path> --tui=false
```

**Comment by zmitchell** [comment]
As a workaround we currently inject a dummy process that simply sleeps forever so that a user can start services again without needing to create a new `process-compose` instance.

**Comment by F1bonacc1** [comment]
Added in v1.18.0

Cheers ✌🏻

**Comment by ri-synth** [comment]
`--keep-project` is the CLI option.
