### ISSUE TITLE
Add command reference to the website

### ISSUE THREAD

**Issue by zmitchell** [F1bonacc1/process-compose#202]
## Feature Request
There are docs for the config file format, but there aren't docs for the CLI commands on the website. 

#### Use Case:
In order to see which options exist you need to actually run the application, and that's not always convenient.

#### Proposed Change:
Generate docs or write minimal docs for each command including which flags exist etc.

#### Who Benefits From The Change(s)?
Everyone

**Comment by F1bonacc1** [comment]
Added in v1.18.0

Cheers ✌🏻
