### ISSUE TITLE
Ability to see process memory footprint

### ISSUE THREAD

**Issue by themartdev** [F1bonacc1/process-compose#204]
## Feature Request
I would like to be able to see the memory footprint of running processes.

#### Use Case:
I want to use process-compose to assist local development of microservices. Sometimes I need several non-dockerized services running at the same time, and seeing memory footprint of individual processes would be a big help to me.

#### Proposed Change:
Add a memory column in the TUI

#### Who Benefits From The Change(s)?
People running long processes like APIs with a considerable memory footprint.

#### Alternative Approaches

**Comment by simon-martineau** [comment]
I have a simple implementation in local, if you think this is okay to be added I can tidy it up and make a PR

**Comment by F1bonacc1** [comment]
Hey @themartdev,
That's a great proposal and I've been considering it for some time now, but unfortunately couldn't find a cross-platform way to implement it.

A PR would be more than welcome if you found something that works!

**Comment by F1bonacc1** [comment]
Merged into v1.9.0

Thanks @themartdev!
