### ISSUE TITLE
add ability to disable the TUI from variable environment

### ISSUE THREAD

**Issue by Sail0rd** [F1bonacc1/process-compose#206]
## Feature Request
I would love to be able to disable the TUI using an environment variable because I use process compose along with devbox (which integrate the tool in their solution) but from the devbox cli i can't disable the TUI and i would like to be able to because that would allow us to copy/paste from the terminal (without the copy/selection issue #116 )

#### Use Case:
when unable to copy from the TUI

#### Proposed Change:
pass an environment variable like PROCESS_COMPOSE_TUI=0

#### Who Benefits From The Change(s)?
devbox users mostly

**Comment by F1bonacc1** [comment]
Hi @Sail0rd 
It's possible to disable TUI with `PC_DISABLE_TUI=1` env variable.
