### ISSUE TITLE
Document support for optionally startable services

### ISSUE THREAD

**Issue by thenonameguy** [F1bonacc1/process-compose#21]
Problem:
I have a relatively large process-compose service graphs, some with services that are seldomly wanted to be running. 
Still whenever they are needed, it would be nice to have the dependency mechanism/retries of process-compose.

Proposal:
Allow process-compose services to be in "Not Started" state by some config parameter, so the TUI user can start/stop them manually.

**Comment by F1bonacc1** [comment]
Hi @thenonameguy 

Have you tried to use the `disabled` flag?
```yaml
some_process:
  command: "..."
  disabled: true
```
It allows you to skip it in execution, but start it manually from TUI if needed.

**Comment by F1bonacc1** [comment]
Good catch @thenonameguy :)
Documented
