### ISSUE TITLE
Add support for configuring keybindings for TUI

### ISSUE THREAD

**Issue by thenonameguy** [F1bonacc1/process-compose#22]
The current keybinding is somewhat cumbersome on Fn Lock laptop keyboards (causing airplane mode to be hit instead `Start` :smile:)
It would be nice if the `process-compose.yml` had some optional top-level action->keybind map that could override the current default bindings.

**Comment by F1bonacc1** [comment]
Hi @thenonameguy 

Good suggestion, I planned some refactoring in that area in any case :)
However, I think process-compose.yml is not the correct place for personalization, since you might want to share your process-compose,yml with other developers.
What do you think about adding a .compose customization file to user's $HOME?

**Comment by thenonameguy** [comment]
If anything it should be [`$XDG_CONFIG_HOME` ](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html), but I much prefer explicit CLI flags so I can decide where I want to host it/template it with an env var.

I would argue that having everything in a `process-compose.yml` is preferable so that the complete behavior of the runtime is described by it, without anything implicit polluting from the user environment. I guess I'm a purist :)

Alternatively, I'm sometimes longing for docker-compose's deep-merge behavior of yml files:
https://docs.docker.com/compose/reference/#specifying-multiple-compose-files

With this you could solve the per-user keybind problem like:
```
process-compose -f process-compose.yml -f process-compose.$USER.yml
```

While also solving the pretty obvious usual BE/FE service split:
```
## backenders run
process-compose -f process-compose.be.yml
## frontenders run
process-compose -f process-compose.be.yml -f process-compose.fe.yml
```

**Comment by F1bonacc1** [comment]
Hi @thenonameguy 

[v0.24.0](https://github.com/F1bonacc1/process-compose/releases/tag/v0.24.0)
Should prevent the airplane mode once and for all 😃

BTW it would be great if you could share your new configuration.
