### ISSUE TITLE
Feature Request - process-compose ls

### ISSUE THREAD

**Issue by brandonbiggs** [F1bonacc1/process-compose#232]
## Feature Request
I'd like to see a shortcut for `process-compose process list` that could be accessible as `process-compose ls`. 

#### Use Case:
To allow for easier adoption from docker-compose, having a command `process-compose ls` would be helpful for listing running processes.

#### Proposed Change:
Add a new command line option `ls` that functions the same way as `process list`.

#### Who Benefits From The Change(s)?
People who are excited to use `process-compose` rather than `docker-compose` but have experience with `docker-compose` and other compose tools that use `ls` as a way to list running processes. 

#### Alternative Approaches
We could make a bash alias instead.

I'd be open to submitting a PR for this if this is something that would be beneficial. I just barely discovered this repo, but am not great with go, so a little explanation or a link to documentation that describes how the app is built would be very much appreciated. :) 

Thanks!

**Comment by brandonbiggs** [comment]
This seems to be really easy to add. One line addition - https://github.com/F1bonacc1/process-compose/blob/2540374e305b0ac683ad88e06c637fe2fa7c0e5c/src/cmd/list.go#L104

`rootCmd.AddCommand(listCmd)`

**Comment by F1bonacc1** [comment]
Added in v1.27.0

Please let me know if everything is as expected.

Cheers!
