### ISSUE TITLE
[Feature Request] process-compose update

### ISSUE THREAD

**Issue by misuzu** [F1bonacc1/process-compose#233]
## Feature Request

I'd like to update an already running `process-compose` instance by passing an updated `process-compose.yaml` file.

#### Use Case:
For example, I have 10 different processes running. I've edited my `process-compose.yaml` file, and now I have to restart all of these processes.

#### Proposed Change:
I'd like to have something like `process-compose update process-compose.yaml`, which should do the following:
1. If there are changes to existing processes in the updated `process-compose.yaml` file, stop the old instances of these processes and start new instances with the updated config. Do not touch other processes.
1. If there are only new processes in the updated `process-compose.yaml` file, start the new processes without affecting the others.
1. If some processes no longer exist in the updated `process-compose.yaml` file, stop only those old processes without touching the others.

This should mimic the behavior of Docker Swarm (`docker stack deploy --prune -c docker-compose.yml mystack`).
#### Who Benefits From The Change(s)?
Everyone who values their time, I guess.

#### Alternative Approaches
Running multiple `process-compose` instances with different sets on processes, which is not convenient.

**Comment by F1bonacc1** [comment]
Added in v1.27.0

**Comment by misuzu** [comment]
> Added in v1.27.0
> 
> Please let me know if everything is as expected.
> 
> Cheers!

Thank you!
I didn't have much time lately but now I've run some tests and found a couple of issues: https://github.com/F1bonacc1/process-compose/issues/283 https://github.com/F1bonacc1/process-compose/issues/284
