### ISSUE TITLE
is_elevated still asks for password even if sudo is using cached credentials

### ISSUE THREAD

**Issue by Enteee** [F1bonacc1/process-compose#250]
#### Version of `process-compose`:

```
$ process-compose version
Process Compose
Version:        v1.27.0
Commit:         2b65c79
Date (UTC):     2024-09-14T20:35:54Z
License:        Apache-2.0
Discord:        https://discord.gg/S4xgmRSHdC

Written by Eugene Berger
```

#### OS environment: 

`nixos` with `devenv.nix`

#### Steps or code to reproduce the issue:

1) start process compose with a process that has `is_elevated: true`
2) type password -> process runs
3) restart process compose

-> elevated process runs directly without waiting for password input, but process compose TUI is still asking for a password.

#### Expected result:

* `process-compose` should not ask for a password if `sudo` is caching credentials

#### Actual result:

* `process-compose` always asks for a password

**Comment by Enteee** [comment]
This also happens when the user does not require a password for sudo (`NOPASSWD`-policy)

**Comment by F1bonacc1** [comment]
> This also happens when the user does not require a password for sudo (`NOPASSWD`-policy)

In the case of NOPASSWD policy, I recommend not using the `is_elevated` flag.

**Comment by Enteee** [comment]
> In the case of NOPASSWD policy, I recommend not using the `is_elevated` flag.

my use case for process-compose is as process manager for my `devenv.nix` powered development environment. I don't really know if the user running my devenv has NOPASSWD configured.

**Comment by F1bonacc1** [comment]
The use case is clear.
Will be fixed in the next release.
