### ISSUE TITLE
change of behavior: `list` hangs PS is not running

### ISSUE THREAD

**Issue by mprimi** [F1bonacc1/process-compose#251]
Hi there, 

I've been using process compose for a couple of years as part of test infrastructure. Works awesome.

Recently there has been a breaking (for us) change of behavior, and I wanted to check that this is working as expected and not a bug.

# v1.6.x
Doing a `process list` when compose is **not running** result in **exit with non-zero exit code**:

```
$ process-compose version
Process Compose
Version:        v1.6.1
Commit:         3cd252d
Date (UTC):     2024-05-17T21:10:25Z
[...]

$ process-compose --port 18080 process list
24-09-24 21:25:03.658 FTL failed to list processes error="Get \"http://localhost:18080/processes\": dial tcp 127.0.0.1:18080: connect: connection refused"
```

# v1.27.x
On a more recent version, `process list` hangs indefinitely if compose is **not running**:

```
$ process-compose version
Process Compose
Version:        v1.27.0
Commit:         2b65c79
Date (UTC):     2024-09-14T20:35:54Z
[...]

$ process-compose --port 18080 process list

^C
```

The 1.27 behavior has no timeout, one of our pipeline had been stuck for 2 days on this.

---

Is the new behavior a bug or a feature?

If it's a bug, I can pin to an older version until it's fixed.
If it's a feature, I'll update my scripts to handle this new behavior (i.e. use some other mechanism to make sure PC is not already running).

Thank you!

p.s. I don't know when this changed, I only know it's between 1.6 and 1.27. But I can find out if you want know and it saves you some time to track it down.

**Comment by F1bonacc1** [comment]
Hi @mprimi,
Thanks for letting me know.
Definitely a bug.
Will be fixed in the next release.

**Comment by mprimi** [comment]
I am sorry, the version number was a red herring!

I had the two versions on two machines, so I assumed that was the cause.
But after downgrading from 1.27 to 1.9 and then 1.6 I was still observing the same behavior.

The hung `process list` was due to a hung `process-compose` that had been running for days but was not answering on the socket!

After killing that zombie process, everything works fine with 1.27...

Sorry for the false alarm! 

Closing and may open a new issue if I see `process-compose` (daemon) hanging again in a similar way.
