### ISSUE TITLE
Feat: show system resource usage

### ISSUE THREAD

**Issue by kran6a** [F1bonacc1/process-compose#254]
## Feature Request
Show overall system resource usage on this section of the TUI.

![image](https://github.com/user-attachments/assets/16dc955b-af42-475e-b7f1-54942be65f86)

The resource usage should show how many resources are used by processes managed by process-compose, how many resources are used by other processes and how many resources are available.

#### Use Case:
Being able to view the aggregated resource usage and capacity without having to use the keyboard to close the TUI, open htop then closing htop and opening the TUI again.

#### Who Benefits From The Change(s)?
I believe most power users out there would consider it a nice QoL change.

#### Alternative Approaches
Closing the process-compose TUI, opening htop then closing htop and opening the TUI again.

**Comment by F1bonacc1** [comment]
Added in v1.34
