### ISSUE TITLE
macOS support

### ISSUE THREAD

**Issue by starcraft66** [F1bonacc1/process-compose#27]
I noticed that the project's README explicitly states that macOS is unsupported. Is it unsupported in the sense that no support will be provided to mac users or that the project flat out doesn't work under macOS?

To be clear, I haven't even attempted to run this on a mac but this project caught my eye because I think it would be interesting to attempt to convert some of my existing docker development workflows on mac to use process-compose instead as it wouldn't require a VM running in the background and gobbling up RAM to operate.

**Comment by F1bonacc1** [comment]
Hi @starcraft66,

This is an excellent question I had been waiting for a long time.
You've probably noticed that I've been compiling a macOS version for many releases now. However, I personally don't have access to a mac computer to actually validate that there are no issues.

If someone will try it and let me know if there are any bugs, issues or if it just works, I will gladly update the readme.

**Comment by thenonameguy** [comment]
The project perfectly works for my x86/m1 darwin teammates (compiled on the host OS via Nix). I think the README can be adjusted to include support.

Additionaly I think Github Actions could be used to run some integration tests on non-linux platforms.

**Comment by F1bonacc1** [comment]
This is awesome @thenonameguy!
Thanks for letting me know.
I will update the Readme

**Comment by starcraft66** [comment]
Thanks for the info, will close.
