### ISSUE TITLE
[Feature Request] Multi process logging

### ISSUE THREAD

**Issue by albertilagan** [F1bonacc1/process-compose#279]
## Feature Request
Similar to how logging is displayed when `tui` is disabled where every logs is showing, it would be nice if we can select which process/es to show logs.

#### Use Case:
I have custom script that utilize `process-compose` cli, e.g `dev logs` triggers `fzf` selection then show logs for the selected process, with this feature I can allow `fzf  --multi` to show logs for those selected processes.

Best paired with `--detach` mode so I don't need to see all process logs,

#### Proposed Change:
```
process-compose process logs app,backend,web
```

#### Alternative Approaches
```
#!/bin/bash

process-compose process logs app --follow &
process-compose process logs engine --follow

# Wait for both commands to finish
wait
```

**Comment by albertilagan** [comment]
when I mention the `showing all logs when tui is disable` it might be a `devenv` feature just in case it confuses someone.

**Comment by F1bonacc1** [comment]
Hey @albertilagan,

I started working on it and I have a clarifying question.
Should the multi log from proc_a and proc_b print as:

Option 1:
```
log from a
log from a
log from b
```

Option 2:
```
[proc_a ] log from a
```

**Comment by albertilagan** [comment]
> Hey @albertilagan,
> 
> 
> 
> I started working on it and I have a clarifying question.
> 
> Should the multi-log from `proc_a` and `proc_b` print as:
> 
> 
> 
> Option 1:
> 
> ```
> 
> log from a
> 
> log from b
> 
> log from a
> 
> ```
> 
> 
> 
> Option 2:
> 
> ```
> 
> [proc_a ] log from a
> 
> [proc_b ] log from b
> 
> [proc_a ] log from a
> 
> ```

I'm a bit torn between the 2 options. Option one is great when copying logs because there wont be extra stuff in the way. But option 2 is great for visibility and groupings. 

I'm leaning towards option 2. But totally open on other option.

**Comment by F1bonacc1** [comment]
Perhaps I will make it configurable.

**Comment by F1bonacc1** [comment]
Added in v1.46.0
Please let me know if everything is as expected.

**Comment by albertilagan** [comment]
> Added in v1.46.0 Please let me know if everything is as expected.

![CleanShot 2024-12-28 at 16 46 13@2x](https://github.com/user-attachments/assets/86ac7790-913b-4737-8f26-9d4f40ec6a93)
Any idea why this is stuck? Is my syntax incorrect?

**Comment by albertilagan** [comment]
> > Added in v1.46.0 Please let me know if everything is as expected.
> 
> ![CleanShot 2024-12-28 at 16 46 13@2x](https://private-user-images.githubusercontent.com/22500561/399065726-86ac7790-913b-4737-8f26-9d4f40ec6a93.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUzNzYxNDQsIm5iZiI6MTczNTM3NTg0NCwicGF0aCI6Ii8yMjUwMDU2MS8zOTkwNjU3MjYtODZhYzc3OTAtOTEzYi00NzM3LThmMjYtOWQ0ZjQwZWM2YTkzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI4VDA4NTA0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0MTVhZjM4NTk5NWI1MzRjMTc4OWRjYTMwZDRmNWE0OTI0OGYyMTY4MDdiNmFlYzI0YjNlYTVkZjM0YjY5ZjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.rPjps3ubjlx2mYyzn1-OKlZy6TmklFgV-wJuFlKcEmU) Any idea why this is stuck? Is my syntax incorrect?

Okay nvm it's working, I forgot to restart process-compose server after upgrading.
