### ISSUE TITLE
feature request: ctrl-r works without focus on top pane

### ISSUE THREAD

**Issue by ryantm** [F1bonacc1/process-compose#282]
Thank you for making process compose, it is very nice to use!

## Feature Request

I've noticed that restarting a process depends on the focus being on the top pane. It does nothing if the focus is on the logs. This makes process-compose feel unresponsive. Either it should let you know it doesn't work, or it should just work. The UI shows Ctrl-R at the bottom as an option, but it does nothing if the logs pane is selected.

#### Use Case:

* I want to restart a process
* I type ctrl+r
* Nothing happens
* I have to learn and remember to click the top pane to have Ctrl-R do something

#### Proposed Change:
* Enable ctrl-r to work no matter where the focus is. Since the UI shows a selected process 

#### Who Benefits From The Change(s)?
* Users who want to restart processes

#### Alternative Approaches
* Don't show ctrl-r as an option when it isn't available
* pop up a modal that says you can't use ctrl-r here when you don't have the top selected

**Comment by F1bonacc1** [comment]
Hi @ryantm,

Thanks for your feedback.
It sounds like a bug, as Ctrl-r should be a global shortcut.
I tried to reproduce that in my environment but couldn't. It works when both the top and bottom parts are selected.
Can you please provide more details? Version, OS, Terminal.

**Comment by ryantm** [comment]
Ah, you're right! I'm sorry, I tried to make a minimal reproduction and it works fine. I'll try to see if I can reproduce consistently with some minimal thing and re-open if I do.

**Comment by ryantm** [comment]
When I upgraded from process-compose v1.24.2 to v1.40.1 for my use case, the problem went away.
