### ISSUE TITLE
Feat: Add tasks => processes that are spawned either manually or on a schedule and are expected to end

### ISSUE THREAD

**Issue by kran6a** [F1bonacc1/process-compose#285]
#### Use Case:
Managing a server usually requires mainteinance tasks (`git pull` to update the services, build scripts to rebuild after a git pull, backing up databases, vacuuming databases, collecting statistics from databases, sending bulk mails, updating the system, updating process-compose, updating node/bun/deno, etc.).

As I would like to use process-compose as my only server management tool, I would like to be able to define those tasks either in the `process-compose.yml` file or in a `task-compose.yml` file so that I can easily manage them from a single place and add them to my git repo so I can track changes on them.

#### Proposed Change:
1. Adding support for tasks to process-compose and a shortcut to change from process view to task view.
2. Tasks should support setting a deadline. If the task does not end by the deadline it is killed and treated as a failed task.
3. (**optional**) Add the ability to define a file to keep track of the last time a task was executed, the time it took and the success/failure outcome so that process-compose know when a periodic task should be executed/retried due to failure after server/process-compose restarts. This information should not persists by default.
4. (**very optional**) Allow defining parameters of type boolean, number and string with optional default values provided in the config file so that when you run a task you are asked for the parameters which are then provided as environment variables to the task's command. (Example: when trying to backup a database ask whether you want to upload it to a remote machine and prefill the response  (of type boolean) with NO, which sets the `UPLOAD_TO_S3` environment variable to 0).

#### Who Benefits From The Change(s)?
System admins who manage simple VPSs, home labs or bare metal servers.

#### Alternative Approaches
Managing tasks as a bunch of `.sh` scripts or package.json scripts on their respective services.

**Comment by F1bonacc1** [comment]
Hey @kran6a,

Thank you for clearly outlining your use case, I think it makes a lot of sense.
However, this proposal deviates from Process Compose philosophy of being the orchestrator of long-running processes.

I am sure you are familiar with an amazing [Task](https://taskfile.dev/) project that does exactly what you described.
I think it will be a better fit for your needs and can easily be embedded as one of the processes in Process Compose.
