### ISSUE TITLE
`go install` doesn't work?

### ISSUE THREAD

**Issue by IngwiePhoenix** [F1bonacc1/process-compose#34]
Ì found another use for `process-compose`: Orchestrating running `rclone` instances on my openwrt router which lacks a more-solid init system that can handle automatic restarts. Technically `procd` can - but I would have to create that for an absurd number of scripts...

So, instead, I will be using `process-compose`. Well, I tried to install it via Go's install command but:

```
root@FriendlyWrt ~/.c/rclone [1]# go install "github.com/f1bonacc1/process-compose@latest"
go: downloading github.com/f1bonacc1/process-compose v0.29.0
go: github.com/f1bonacc1/process-compose@latest: module github.com/f1bonacc1/process-compose@latest found (v0.29.0), but does not contain package github.com/f1bonacc1/process-compose
```

Mind looking into this? :)

**Comment by F1bonacc1** [comment]
Hi @IngwiePhoenix,

The reason this command doesn't work is the fact that I keep my `main` package under the `src` directory. Theoretically this command should have worked for you:
`go install "github.com/f1bonacc1/process-compose/src@latest"`

But if you will run it you will see a criptic message which is discussed at length here: https://github.com/golang/go/issues/44840

To make a long story short - there is a long-standing PR: https://github.com/InVisionApp/go-health/pull/77 which the author of this package doesn't accept for some reason. So I am building with a local fork, which requires a `replace` directive in the `go.mod` file which is not supported by `go install`

Alternatives:
1. You can always run `wget https://github.com/F1bonacc1/process-compose/releases/download/v0.29.0/process-compose-linux-arm` I am assuming that your router is arm based.
2. If you need a one-liner for the latest version there is this monstrosity:
```shell
curl -s https://api.github.com/repos/f1bonacc1/process-compose/releases/latest  \
| grep "browser_download_url.*linux-arm\"" \
| cut -d : -f 2,3 \
| tr -d \" \
| wget -qi -
```

Hope it helps.
