### ISSUE TITLE
Logging only to file by default is confusing

### ISSUE THREAD

**Issue by daisylb** [F1bonacc1/process-compose#37]
I was trying to get set up with process-compose, and I had an error in my YAML. I spent far too long scratching my head at why it was exiting `1` with no output, and had to do a fair amount of source code digging to discover that it was logging an error message to `$TMPDIR/process-compose-daisy.yaml`.

IMO it would be good if the default was to log to stdout, at least until the TUI starts up, or failing that to print a message explaining where the log file is.

**Comment by F1bonacc1** [comment]
Hi @daisylb,
You are right, there is an area for improvement there.
I will add a clear message on startup about the default log location and improve the documentation.

**Comment by F1bonacc1** [comment]
Hi @daisylb 

The situation is somewhat improved in [v0.29.4](https://github.com/F1bonacc1/process-compose/releases/tag/v0.29.4)
Let me know if the syntax issue that you had is logged as expected with the new version.
