### ISSUE TITLE
Processes are still running after killing main process

### ISSUE THREAD

**Issue by shyim** [F1bonacc1/process-compose#38]
Hey,

When I stop, the terminal or `kill PID-OF-PROCESS-COMPOSE` my started process is still there. Pressing `CONTROL+C` quits it normally.

The default signal type is TERM by macOS

**Comment by F1bonacc1** [comment]
Hi @shyim,
Can you please share your configuration and logs?

**Comment by F1bonacc1** [comment]
Hi @shyim,

This issue should be resolved in [v0.29.7](https://github.com/F1bonacc1/process-compose/releases/tag/v0.29.7)
Please confirm for your scenario.

**Comment by shyim** [comment]
They are still running for me on Mac. Build the main branch.

```
processes:
  test:
    command: "php -S 127.0.0.1:5000 -t ."
```

I just did nix-shell -p go php, build process compose and executed that config and afterward `kill PID`

**Comment by F1bonacc1** [comment]
Didn't expect you to build from source :)
Now the changes are in the main branch.
Try again?

**Comment by shyim** [comment]
Ahh lol 🤣. The nix run of this repo was outdated. I will try again later

**Comment by shyim** [comment]
Confirmed working thanks!

**Comment by GTrunSec** [comment]
Yeh, can be sure `With --tui=false flag it did worked`
but, how about with --tui=true. I git the same problem,.
