### ISSUE TITLE
After C-c process the tasks are still nohup

### ISSUE THREAD

**Issue by GTrunSec** [F1bonacc1/process-compose#43]
```
process-compose version  
Process Compose
Version:        v0.40.0
Commit:         db93aa4
Date (UTC):     20230122201755
License:        Apache-2.0
```
case: running a flask python web.

```
[//example/composeJobs/hello_1  ] *** Operational MODE: single process ***
[//example/composeJobs/hello_1  ] WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0xd2a750 pid: 1541517 (default app)
[//example/composeJobs/hello_1  ] *** uWSGI is running in multiple interpreter mode ***
[//example/composeJobs/hello_1  ] spawned uWSGI worker 1 (and the only) (pid: 1541517, cores: 1)
^C%                                                                                                                      

guangtao in 🌐 Desktop in cells-lab on  main [!?] via 🐍 v3.10.9 took 20s 
❯ ps aux | grep ./hello.py

guangtao 1541517  0.5  0.0 259096 31536 pts/2    S    22:26   0:00 /nix/store/r09q26lws8grvk6vasj398ig02nhpbmi-uwsgi-2.0.21/bin/uwsgi --plugin=python3 --http :9091 -H /nix/store/mfsp48c1khbv29wd23rqcwagr28bryis-python3-3.10.9-env --callable app --wsgi-file ./hello.py

guangtao 1541518  0.0  0.0  18640  5896 pts/2    S    22:26   0:00 /nix/store/r09q26lws8grvk6vasj398ig02nhpbmi-uwsgi-2.0.21/bin/uwsgi --plugin=python3 --http :9091 -H /nix/store/mfsp48c1khbv29wd23rqcwagr28bryis-python3-3.10.9-env --callable app --wsgi-file ./hello.py
```

Expected:

- after C-g or `process-compose` exits, the related tasks should be hung up.

**Comment by F1bonacc1** [comment]
Hi @GTrunSec,

Are those forked processes that are running after you exit `process-compose`?
Can you execute
`ps aux | grep ./hello.py`
Before and After exiting the `process-compose`?

Also, it will be helpful if you could share the actual part of YAML that causes this behavior.

**Comment by GTrunSec** [comment]
Sorry about that,

It looks like caused by `set options`

```
#!/nix/store/pj1hnyxhcsw1krmhnbb9rjvqssbzliw8-bash-5.2-p15/bin/bash
# shellcheck shell=bash
set -o errexit
set -o pipefailset -o nounset
set -o functraceset -o errtraceset -o monitor
set -o posix
shopt -s dotglob

export PYTHON="${PYTHON:-/nix/store/mfsp48c1khbv29wd23rqcwagr28bryis-python3-3.10.9-env}"

/nix/store/r09q26lws8grvk6vasj398ig02nhpbmi-uwsgi-2.0.21/bin/uwsgi --plugin=python3 --http :9091 -H "$PYTHON" --callable 
app \
--wsgi-file ./hello.py
```

**Comment by GTrunSec** [comment]
can be sure I should remove `set -o monitor`. let me close this issue. thanks

**Comment by GTrunSec** [comment]
after removing `set -o monitor`, most bashScripts are going to well. But I found a special case that is docker-compose up with `-d` flag.

@F1bonacc1 Could you reproduce that? thanks

```
 process-compose -f ./test.yaml docker-compose  
```

**Comment by F1bonacc1** [comment]
This is what is called a daemon (-d) process.
There is a special configuration required for that. Please check the documentation here:
https://github.com/F1bonacc1/process-compose#-background-detached-processes

**Comment by F1bonacc1** [comment]
Can you please share your YAML?
What are your expectations from this command:
`process-compose -f ./test.yaml docker-compose`
I am not sure what it should do.

**Comment by GTrunSec** [comment]
```

**Comment by F1bonacc1** [comment]
And then the `docker-compose` keeps running when you close the shell (SIGHUP) or when you terminate the `process-compose` with CTRL+C (SIGTERM)?

**Comment by GTrunSec** [comment]
> 
And then the docker-compose keeps running when you close the shell (SIGHUP) or when you terminate the process-compose with CTRL+C (SIGTERM)?

Yes, But the tui mode doesn't have this issue.

**Comment by F1bonacc1** [comment]
I managed to reconstruct it.
It happens only with docker-compose.
Will look into it.

**Comment by GTrunSec** [comment]
weird, if you run the docker-compose command directly on the TUI mode, no process hangups. but if you run that command from bashScript, the issue will have.

```
test:
  command: "/nix/store/w8p7bz0zc6lbqq4na3vxpgj1fjq3jmg7-docker-compose-2.15.1/bin/docker-compose -f              
 /nix/store/jg4ac1r1wbf2a0a1db4hydc40khmza0j-dockerCompose.yaml up" 
```

**Comment by thenonameguy** [comment]
Bash does not automatically forward signals to subprocesses.

Try prepending 'exec'.

**Comment by F1bonacc1** [comment]
Hi @GTrunSec,

Can you please check if v0.40.1 fixed the issue for you?

**Comment by GTrunSec** [comment]
thanks  @F1bonacc1  it works well on my latest [rev](https://github.com/GTrunSec/DeSci/pull/14#issuecomment-1407905370), and @thenonameguy your `exec` tips.
