### ISSUE TITLE
provide `logs` sub-command for tailing process logs 

### ISSUE THREAD

**Issue by adrian-gierakowski** [F1bonacc1/process-compose#47]
so that I could simply do `process-compose logs -f my-service-name` instead of: `tail -f path/to/log/file.log`

why: cause I don't want to remember and type in the `path/to/log/file.log` for each service

**Comment by adrian-gierakowski** [comment]
`process-compose logs` withouth the `service-name` should tail logs from all services

**Comment by F1bonacc1** [comment]
@adrian-gierakowski,

Thanks for this proposal.
Just to make sure, you are talking about a secondary (client) process-compose process that retrieves the logs from the primary (server) process-compose?

**Comment by adrian-gierakowski** [comment]
Yes!

**Comment by F1bonacc1** [comment]
Hey @adrian-gierakowski 

I added the logs tailing support in v0.43.1, but without the ability to tail all the processes at the same time.
It would have added too much complexity and created disparity with the TUI in which that is also not possible.

I hope this is not a deal breaker for you :)
Thanks again for the suggestion, this is an absolute must for `process-compose`!

**Comment by adrian-gierakowski** [comment]
Amazing, will give it a try later this week. Thanks!

**Comment by F1bonacc1** [comment]
Please create a new issue if anything is not as expected.
