### ISSUE TITLE
Feature request: brew/scoop package

### ISSUE THREAD

**Issue by pomdtr** [F1bonacc1/process-compose#52]
It is quite trivial to publish your app as a brew/scoop package once you have goreleaser setup, but it really streamlines the installation process.

You can take my repo as an example: https://github.com/pomdtr/sunbeam/blob/main/.goreleaser.yaml#L51

**Comment by F1bonacc1** [comment]
Hi @pomdtr,

Sounds reasonable, I'll look into that.

**Comment by F1bonacc1** [comment]
Added in v0.45.0
