### ISSUE TITLE
Cannot copy TUI text on Mac

### ISSUE THREAD

**Issue by Izhaki** [F1bonacc1/process-compose#54]
Using TUI with selection on, there seem to be no keyboard shortcut to copy the selection.

CTRL-C attempts to kill the process.
CMD-C just blips.

Any idea how this can be done?

**Comment by Izhaki** [comment]
It does. Ha.

Even after you said it took me a while to find this: 

> the logs Title should change to Press Enter to Copy

Thanks!

**Comment by mikenikles** [comment]
I can't find the answer in the GitHub repo or the docs: How do I enable selection mode?

**Comment by F1bonacc1** [comment]
Hi @mikenikles,
It is hidden if you use Wayland. If not the default shortcut is `CTRL+S`

**Comment by mikenikles** [comment]
🫣 It's literally listed in the shortcuts dialog... Thanks for pointing me to the obvious :).
