### ISSUE TITLE
do not evaluate `log_location` until decide to start process

### ISSUE THREAD

**Issue by dzmitry-lahoda** [F1bonacc1/process-compose#58]
## Feature Request

use `log_location` only when going to start process

#### Use Case:

process with log_location depends on other process before to create folder

#### Proposed Change:

only before process start, try to create log file.

may be write warning on overall compose start

#### Who Benefits From The Change(s)?

me

#### Alternative Approaches

wrapper around compose to run some script before to setup folders, like in docker compose mounts?

**Comment by F1bonacc1** [comment]
Hi @dzmitry-lahoda 

Added this in [v0.51.4](https://github.com/F1bonacc1/process-compose/releases/tag/v0.51.4)
