### ISSUE TITLE
donate button in crypto

### ISSUE THREAD

**Issue by dzmitry-lahoda** [F1bonacc1/process-compose#60]
i use this cool tool in crypto, payed in crypto, so can donate in any crypto of choice :) 

thank you for considering adding such button :)

**Comment by F1bonacc1** [comment]
Thank you for offering to support the project :)
It's at the bottom of the (too long) readme - [here](https://github.com/F1bonacc1/process-compose#consider-supporting-the-project-%EF%B8%8F).
