### ISSUE TITLE
show open ports of running processes on linux

### ISSUE THREAD

**Issue by dzmitry-lahoda** [F1bonacc1/process-compose#62]
## Feature Request

Show ports on which processes listen

#### Use Case:

So users can find out ports to connect to

#### Proposed Change:

So make these visible via cli or tui

#### Who Benefits From The Change(s)?

Same feature as in docker shows all listen ports

#### Alternative Approaches

use native linux tooling, so it is not so easy

**Comment by F1bonacc1** [comment]
Hmmm,

That's a challenging one. I am not sure there is a cross platform way to display all the used ports by the running processes.
Will it help if I add something like `processes.proc_name.used_ports`, which will be manually filled by the user and I'll show them in TUI in process info `F3`?

**Comment by dzmitry-lahoda** [comment]
yeah, that is i can do without tui and that i want to avoid. so i guess for linux it can be conditionally robust, just show n/a if it fails to get ports.

**Comment by F1bonacc1** [comment]
Will it work for you if I show them in the process info dialog (`F3`)?

**Comment by F1bonacc1** [comment]
Added in v0.60.0
Feel free to reopen if it doesn't work as expected.
