### ISSUE TITLE
process stop to support list of processes

### ISSUE THREAD

**Issue by dzmitry-lahoda** [F1bonacc1/process-compose#65]
## Feature Request

I can do 
```
process stop my1
process stop my2
```

I cannot 
```
process stop my1 my2
```

#### Use Case:

```
process list | xargs process stop
```

like with docker
```
docker ps -aq | xargs docker stop 
```

#### Who Benefits From The Change(s)?

Like docker.

#### Alternative Approaches

for loop or something more complicated than xargs

**Comment by F1bonacc1** [comment]
Added in v0.60.0
Feel free to reopen if it doesn't work as expected.
