### ISSUE TITLE
Allow runnning executables directly without shell wrapper 

### ISSUE THREAD

**Issue by adrian-gierakowski** [F1bonacc1/process-compose#88]
## Feature Request

I’d like to be able to specify a command as a list of: [executable, args…] and have it ran directly instead of via a shell. 

Note that I’m willing to implement this. 

#### Use Case:

Reducing dependencies needed to run the processes or double-wrapping in a shell, if my executable is already a shell script, which calls other executables. 

#### Proposed Change:

Allow process.command to be an array, in which case it would be invoked directly 

#### Who Benefits From The Change(s)?

People wanting to minimise the deps of their projects.

#### Alternative Approaches

Not sure.

**Comment by adrian-gierakowski** [comment]
seems like union types are a pain in go (I'm might be wrong since I have very little experience with this language) so making command a `string | []string` might not be the best choice 

Adding optional `args []string` and a `bool` flag to disable shell for given process would probably make more sense, although would result in a more verbose config

**Comment by F1bonacc1** [comment]
Hi @adrian-gierakowski,

That's an interesting proposal. Will it work for you to replace the command with `${COMMAND_WITH_ARGS_FOR_SOME_PROC}` environment variable place holder and provide the value for the env variable externally?

**Comment by adrian-gierakowski** [comment]
> That's an interesting proposal. Will it work for you to replace the command with `${COMMAND_WITH_ARGS_FOR_SOME_PROC}`

I think an array filed is required to simplify passing of args with spaces  

I've included a draft implementation in https://github.com/F1bonacc1/process-compose/pull/89

**Comment by F1bonacc1** [comment]
#89 Is merged in v0.75.1
